{
 "title": "Ampere Altra BMC Sensor Monitor",
 "description": "Collects and displays  information about voltage, current, power, status, temperature on Ampere BMC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bmcip",
    "label": "BMCIP:",
    "query": "label_values(ipmi_sensor, server)"
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "content": "# Dashboard Ampere BMC Dashboard\n\n\n\n## Developed by:\n\nRichard Liu "
  },
  {
   "title": "Battery Temperature",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 0 },
   "format": "watt",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"total_power\"}",
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "upsBatteryTemperature" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Power Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"total_power\"}",
     "legendFormat": "total_power"
    }
   ]
  },
  { "title": "Voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "S0 CPU Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_cpu_vcore\"}",
     "legendFormat": "s0_cpu_vcore"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_3v3_cpu\"}",
     "legendFormat": "3v3_cpu"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_soc_volt\"}",
     "legendFormat": "s0_soc_volt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_0v8_vddc_soc\"}",
     "legendFormat": "s0_0v8_vddc_soc"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_1v8_soc\"}",
     "legendFormat": "s0_1v8_soc"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_0v75_pcp\"}",
     "legendFormat": "s0_0v75_pcp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_1v8_pcp\"}",
     "legendFormat": "s0_1v8_pcp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_0v85_rca\"}",
     "legendFormat": "s0_0v85_rca"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_rca_vr_volt\"}",
     "legendFormat": "s0_rca_vr_volt"
    }
   ]
  },
  {
   "title": "S1 CPU Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_cpu_vcore\"}",
     "legendFormat": "s1_cpu_vcore"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_3v3_cpu\"}",
     "legendFormat": "s1_3v3_cpu"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_soc_volt\"}",
     "legendFormat": "s1_soc_volt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_0v8_vddc_soc\"}",
     "legendFormat": "s1_0v8_vddc_soc"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_1v8_soc\"}",
     "legendFormat": "s1_1v8_soc"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_0v75_pcp\"}",
     "legendFormat": "s1_0v75_pcp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_1v8_pcp\"}",
     "legendFormat": "s1_1v8_pcp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_0v85_rca\"}",
     "legendFormat": "s1_0v85_rca"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_rca_vr_volt\"}",
     "legendFormat": "s1_rca_vr_volt"
    }
   ]
  },
  {
   "title": "DDR Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_0v6_vtt0123\"}",
     "legendFormat": "s0_0v6_vtt0123"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_0v6_vtt4567\"}",
     "legendFormat": "s0_0v6_vtt4567"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_1v2_vddq0123\"}",
     "legendFormat": "s0_1v2_vddq0123"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_1v2_vddq4567\"}",
     "legendFormat": "s0_1v2_vddq4567"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_dimm_ddr_volt\"}",
     "legendFormat": "s0_dimm_ddr_volt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_dimm_vr1_volt\"}",
     "legendFormat": "s0_dimm_vr1_volt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_dimm_vr2_volt\"}",
     "legendFormat": "s0_dimm_vr2_volt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_dimm_ddr_volt\"}",
     "legendFormat": "s1_dimm_ddr_volt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_0v6_vtt0123\"}",
     "legendFormat": "s1_0v6_vtt0123"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_0v6_vtt4567\"}",
     "legendFormat": "s1_0v6_vtt4567"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_1v2_vddq0123\"}",
     "legendFormat": "s1_1v2_vddq0123"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_1v2_vddq4567\"}",
     "legendFormat": "s1_1v2_vddq4567"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_dimm_vr1_volt\"}",
     "legendFormat": "s1_dimm_vr1_volt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_dimm_vr2_volt\"}",
     "legendFormat": "s1_dimm_vr2_volt"
    }
   ]
  },
  {
   "title": "PSU Input Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"psu1_vin\"}",
     "legendFormat": "psu1_vin"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"psu2_vin\"}",
     "legendFormat": "psu2_vin"
    }
   ]
  },
  {
   "title": "BMC Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"3v3_bmc\"}",
     "legendFormat": "3v3_bmc"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"5v_bmc\"}",
     "legendFormat": "5v_bmc"
    }
   ]
  },
  {
   "title": "MISC Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"2v5\"}",
     "legendFormat": "2v5"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"3v3\"}",
     "legendFormat": "3v3"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s0_soc_temp\"}",
     "legendFormat": "s0_soc_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s0_soc_vrd_temp\"}",
     "legendFormat": "s0_soc_vrd_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s0_core_vrd_temp\"}",
     "legendFormat": "s0_core_vrd_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s1_soc_temp\"}",
     "legendFormat": "s1_soc_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s1_soc_vrd_temp\"}",
     "legendFormat": "s1_soc_vrd_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s1_core_vrd_temp\"}",
     "legendFormat": "s1_core_vrd_temp"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s0_dimm_vrd_temp\"}",
     "legendFormat": "s0_dimm_vrd_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s0_dimmg0_temp\"}",
     "legendFormat": "s0_dimmg0_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s1_dimm_vrd_temp\"}",
     "legendFormat": "s1_dimm_vrd_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s1_dimmg0_temp\"}",
     "legendFormat": "s1_dimmg0_temp"
    }
   ]
  },
  {
   "title": "MISC Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s0_rca_vr_temp\"}",
     "legendFormat": "s0_rca_vr_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"s1_rca_vr_temp\"}",
     "legendFormat": "s1_rca_vr_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"nvmebp_maxtemp\"}",
     "legendFormat": "nvmebp_maxtemp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"nvmem2_maxtemp\"}",
     "legendFormat": "nvmem2_maxtemp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"ocp_temp\"}",
     "legendFormat": "ocp_temp"
    }
   ]
  },
  {
   "title": "PSI Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"psu1_temp\"}",
     "legendFormat": "psu1_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"psu2_temp\"}",
     "legendFormat": "psu2_temp"
    }
   ]
  },
  {
   "title": "Room Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "multifile_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Case Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"ts1_temp\"}",
     "legendFormat": "ts1_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"ts2_temp\"}",
     "legendFormat": "ts2_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"ts3_temp\"}",
     "legendFormat": "ts3_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"ts4_temp\"}",
     "legendFormat": "ts4_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"ts5_temp\"}",
     "legendFormat": "ts5_temp"
    }
   ]
  },
  {
   "title": "Room Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "multifile_humidityrelative", "legendFormat": "Humidity" }
   ]
  },
  { "title": "Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "CPU Power",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_cpu_pwr\"}",
     "legendFormat": "s0_cpu_pwr"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_cpu_pwr\"}",
     "legendFormat": "s1_cpu_pwr"
    }
   ]
  },
  {
   "title": "DDR Power",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_mem_pwr\"}",
     "legendFormat": "s0_mem_pwr"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_dimm_vr1_pwr\"}",
     "legendFormat": "s0_dimm_vr1_pwr"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_dimm_vr2_pwr\"}",
     "legendFormat": "s0_dimm_vr2_pwr"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_mem_pwr\"}",
     "legendFormat": "s1_mem_pwr"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_dimm_vr1_pwr\"}",
     "legendFormat": "s1_dimm_vr1_pwr"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_dimm_vr2_pwr\"}",
     "legendFormat": "s1_dimm_vr2_pwr"
    }
   ]
  },
  {
   "title": "Total Power Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"cpu_power\"}",
     "legendFormat": "CPU Power"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"dimm_vr1_power\"}\n",
     "legendFormat": "DIMM 1 Power"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"dimm_vr2_power\"}\n",
     "legendFormat": "DIMM 2 Power"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"mem_power\"}\n",
     "legendFormat": "Memory Power"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"total_power\"}\n",
     "legendFormat": "Total Power"
    }
   ]
  },
  {
   "title": "PSU Power Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"psu1_pout\"}",
     "legendFormat": "psu1_pout"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"psu2_pout\"}",
     "legendFormat": "psu2_pout"
    }
   ]
  },
  {
   "title": "MISC  Power Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s0_rca_vr_pwr\"}",
     "legendFormat": "s0_rca_vr_pwr"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"s1_rca_vr_pwr\"}",
     "legendFormat": "s1_rca_vr_pwr"
    }
   ]
  },
  { "title": "FAN Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan3_1_speed\"}",
     "legendFormat": "fan3_1_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan3_2_speed\"}",
     "legendFormat": "fan3_2_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan4_1_speed\"}",
     "legendFormat": "fan4_1_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan4_2_speed\"}",
     "legendFormat": "fan4_2_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan5_1_speed\"}",
     "legendFormat": "fan5_1_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan5_2_speed\"}",
     "legendFormat": "fan5_2_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan6_1_speed\"}",
     "legendFormat": "fan6_1_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan6_2_speed\"}",
     "legendFormat": "fan6_2_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan7_1_speed\"}",
     "legendFormat": "fan7_1_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan7_2_speed\"}",
     "legendFormat": "fan7_2_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan8_1_speed\"}",
     "legendFormat": "fan8_1_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"fan8_2_speed\"}",
     "legendFormat": "fan8_2_speed"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"psu1_fan_speed\"}",
     "legendFormat": "psu1_fan_speed"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"psu2_fan_speed\"}",
     "legendFormat": "psu2_fan_speed"
    }
   ]
  }
 ]
}